# DG-LAB 设备波形预设配置文件
# 每个波形预设包含一系列(wave_x, wave_y, wave_z)参数组
# 设备会按顺序循环这些参数组，创建不同效果的波形

# 波形参数说明:
# wave_x: 波形宽度 (0-31)
# wave_y: 波形强度 (0-1023)
# wave_z: 波形频率 (0-31)

# 波形预设定义
presets:
  # 加速波形 - 逐渐增加频率
  Going_Faster:
    - [5, 135, 20]
    - [5, 125, 20]
    - [5, 115, 20]
    - [5, 105, 20]
    - [5, 95, 20]
    - [4, 86, 20]
    - [4, 76, 20]
    - [4, 66, 20]
    - [3, 57, 20]
    - [3, 47, 20]
    - [3, 37, 20]
    - [2, 28, 20]
    - [2, 18, 20]
    - [1, 14, 20]
    - [1, 9, 20]

  # 恒定波形 - 单一参数，稳定输出
  Constant:
    - [8, 512, 15]

  # 脉冲波形 - 强度和静止交替
  Pulse:
    - [10, 600, 15]
    - [0, 0, 0]

  # 波浪波形 - 强度周期性变化
  Wave:
    - [5, 200, 10]
    - [8, 300, 15]
    - [12, 400, 20]
    - [15, 500, 25]
    - [12, 400, 20]
    - [8, 300, 15]

  # 历史遗留波形
  Intense:
    - [15, 700, 25]
    - [20, 800, 30]
    - [25, 900, 30]
    - [20, 800, 30]
    - [15, 700, 25]
    - [0, 0, 0]

  # 历史遗留波形
  Rhythm:
    - [15, 600, 20]
    - [0, 0, 0]
    - [15, 600, 20]
    - [0, 0, 0]
    - [15, 600, 20]
    - [0, 0, 0]
    
  # 渐强波形 - 强度逐渐增加
  Crescendo:
    - [5, 100, 15]
    - [8, 200, 15]
    - [10, 300, 20]
    - [12, 400, 20]
    - [15, 500, 25]
    - [18, 600, 25]
    - [20, 700, 30]

  # 历史遗留波形
  DoublePeak:
    - [10, 400, 20]
    - [15, 700, 25]
    - [10, 400, 20]
    - [5, 200, 15]
    - [10, 400, 20]
    - [15, 700, 25]
    - [10, 400, 20] 